// Generated by Wrangler on Tue Dec 03 2024 23:01:20 GMT+0100 (heure normale d’Europe centrale)
// by running `wrangler types`

interface Env {
	novelum: R2Bucket;
	DB: D1Database;
	STRIPE_PUBLIC_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SIGNING_SECRET: string;
}
