// Generated by Wrangler by running `wrangler types`

interface Env {
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	STRIPE_PUBLIC_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SIGNING_SECRET: string;
	DISCORD_CONTACT_FORM_WEBHOOK: string;
	DISCORD_PAYMENT_WEBHOOK: string;
	DISCORD_DEVIS_WEBHOOK: string;
	novelum: R2Bucket;
	DB: D1Database;
}
