#:schema node_modules/wrangler/config-schema.json
name = "novelum"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./build/client"

# Configuration globale
[[d1_databases]]
binding = "DB"
database_name = "prod-d1-novelum"
database_id = "65616c94-d0e9-49c5-a744-38203f0eb799"
migrations_dir = "drizzle"

[[r2_buckets]]
bucket_name = "novelum"
binding = "novelum"

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

[env.production]
# Ajouter ici les configurations manquantes
[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-d1-novelum"
database_id = "65616c94-d0e9-49c5-a744-38203f0eb799"
migrations_dir = "drizzle"

[[env.production.r2_buckets]]
bucket_name = "novelum"
binding = "novelum"

# Variables spécifiques à la production
[env.production.vars]
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsubm92ZWx1bS1yYWRpby5mciQ"
STRIPE_PUBLIC_KEY = "pk_live_51PzIAmK2vz4LQjc1NmEONLrA7NZdXjDe6NAHHIFR4C4OoBUOW9of6844lzRzkoQZN6A6ekJ9LFTnXTwhfX8fBg9000yq5ehPoR"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
