#:schema node_modules/wrangler/config-schema.json
name = "novelum"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "prod-d1-novelum"
database_id = "65616c94-d0e9-49c5-a744-38203f0eb799"
migrations_dir = "drizzle"

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

# [env.production.vars]
# API_KEY = "abc123"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
